version: "3.7"

services:
  testbase:
    container_name: base
    build:
      context: .
      args:
          USER_ID: ${USER_ID:-1000}
          GROUP_ID: ${GROUP_ID:-1000}
          USER_NAME: ${USER_NAME:-ironman}
          GROUP_NAME: ${GROUP_NAME:-avengers}
    image: base-img
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      # docker
      - /var/run/docker.sock:/var/run/docker.sock
      # display
      - /tmp/.X11-unix:/tmp/.X11-unix
      # souce
      - ../..:/home/${USER_NAME:-ironman}/src
    network_mode: "host"
